baseurl = ""
languageCode = "en-us"
paginate = 5

[params]
  contentTypeName = "blog"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = false

[languages]
  [languages.en]
    title = "archgaelix"
    description = "seshalja.in's devblog"
    keywords = ""
    author = "Seshal Jain"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "January 02, 2006"
    dateFormatList = "January 02, 2006"

    [languages.en.params.logo]
      logoText = "archgaelix"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "uses"
        name = "Uses"
        url = "/uses"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "dsa"
        name = "DSA"
        url = "/dsa"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
