baseurl = ""
languageCode = "en-us"
paginate = 5


title = "archgaelix"
description = "seshalja.in's devblog"
keywords = ""
author = "Seshal Jain"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "January 02, 2006"
dateFormatList = "January 02, 2006"

[params]
  contentTypeName = "blog"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = false
[params.logo]
  logoText = "archgaelix"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 1
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/blog"
    weight = 2
  [[menu.main]]
    identifier = "talks"
    name = "Git & VC Slides"
    url = "/talks/git-and-version-control/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
