#+title: Uses

These are the tools I use regularly. Check out other cool setups at [[https://uses.tech/]] :computer:

I'm mostly active on my 12.5" Dell Latitude E7250 Ultrabook. Although slightly aged, it is super-lightweight (1200g) and I enjoy typing on the chiclet keyboard. \\
Ubuntu 20.04 with GNOME is my primary OS; I'm testing out Manjaro i3 on a VM (exploring ArchLinux atm). \\
I'm looking forward to switching to the [[https://www.kaufmann.no/roland/dvorak/][Programmer Dvorak]] keyboard layout ASAP; currently I keep dual layouts and practice on [[https://monkeytype.com/][MonkeyType]] whenever I get a chance.

[[https://www.gnu.org/software/emacs/][Emacs 27.1]] is my go-to program for almost anything related to text, with [[https://code.visualstudio.com/][VS Code]] coming in when in a pinch, especially for web-related projects. \\
I use the [[https://draculatheme.com/][Dracula theme]] with [[https://typeof.net/Iosevka/][Iosevka]] as the monospace font. I love [[https://rsms.me/inter/][Inter]] for UI, in fact this website uses Inter as the primary typeface.

[[https://www.mozilla.org/en-US/firefox/browsers/][Firefox]] is my browser of choice and [[https://www.google.com/chrome/][Google Chrome]] for times when Firefox falls short. [[https://github.com/gorhill/uBlock][uBlock Origin]] efficiently blocks ads on the browsers for me.

I read digitally on [[https://johnfactotum.github.io/foliate/][Foliate]] on PC, [[https://readera.org/en/book-reader][ReadEra]] on mobile and my Kindle Paperwhite.

** This website's tech stack
:PROPERTIES:
:CUSTOM_ID: this-websites-tech-stack
:END:

/KISS --- Keep it simple, stupid!/

This blog is generated by [[https://gohugo.io][Hugo]] with the [[https://github.com/panr/hugo-theme-hello-friend][Hello Friend]] theme. The site is stored on Github and deployed via Vercel. Hopefully, I'll transition to my own design soon! \\
All pre- & post-processing of source files is handled natively by Hugo via Hugo Pipes. \\
I like the simplicity of the setup, and avoid bringing in unnecessary JS build tools. But hey --- to each, their own.

{{< endline >}}
